name: 🚀 Auto Deploy Backend to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: 📁 Setup SSH
        run: |
          mkdir -p ~/.ssh
          install -m 600 -D /dev/null ~/.ssh/github-actions
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github-actions
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

          echo "Host ${{ secrets.SSH_HOST }}" >> ~/.ssh/config
          echo "  HostName ${{ secrets.SSH_HOST }}" >> ~/.ssh/config
          echo "  User ${{ secrets.SSH_USER }}" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/github-actions" >> ~/.ssh/config
          echo "  IdentitiesOnly yes" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config

      - name: 🚀 SSH and Deploy BE
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            echo "📥 Pulling latest code..."
            cd ${{ secrets.BE_DIR }}
            git pull origin ${{ secrets.MAIN_BRANCH }}
            echo "📦 Installing dependencies..."
            npm install
            echo "🔁 Restarting PM2 process..."
            pm2 restart server  
          EOF

      - name: 🧹 Cleanup SSH
        run: rm -rf ~/.ssh
